Update Infra-main.yml

diff --git a/.github/workflows/Infra-main.yml b/.github/workflows/Infra-main.yml
--- a/.github/workflows/Infra-main.yml
+++ b/.github/workflows/Infra-main.yml
@@ -103,10 +103,12 @@ jobs:
 
       - name: Check if tfplan.binary exists
         run: |
-          if [ ! -f ./Infra/tfplan.binary ]; then
-            echo "tfplan.binary not found!"
-            exit 1
-          fi
+         ls -l ./Infra
+         if [ ! -f ./Infra/tfplan.binary ]; then
+           echo "tfplan.binary not found!"
+           exit 1
+         fi
+
 
       - name: Convert Plan to JSON
         run: terraform show -json ./Infra/tfplan.binary > ./Infra/tfplan.json
