Update Infra-main.yml

diff --git a/.github/workflows/Infra-main.yml b/.github/workflows/Infra-main.yml
--- a/.github/workflows/Infra-main.yml
+++ b/.github/workflows/Infra-main.yml
@@ -101,6 +101,13 @@ jobs:
         run: terraform plan -var-file="../environments/dev/terraform.tfvars" -out=tfplan.binary
         working-directory: ./Infra
 
+      - name: Check if tfplan.binary exists
+        run: |
+          if [ ! -f ./Infra/tfplan.binary ]; then
+            echo "tfplan.binary not found!"
+            exit 1
+          fi
+
       - name: Convert Plan to JSON
         run: terraform show -json ./Infra/tfplan.binary > tfplan.json
 
